import type { LearningProject, ProfessionalApp, ShowcaseProject } from "@/types/projectArchive";

export const professionalApps: ProfessionalApp[] = [
  {
    name: "Zurich Cyber",
    label: "Contributed",
    icon: "/professional-apps/zurich-cyber.png",
    href: "https://apps.apple.com/ch/app/zurich-cyber-security/id6476657273?l=en-GB",
  },
  {
    name: "Boxx Cyber",
    label: "Contributed",
    icon: "/professional-apps/boxx-cyber.png",
    href: "https://apps.apple.com/us/app/boxx-cyber-security/id6752987257",
  },
  {
    name: "VPN TomatoLink",
    label: "Built end-to-end",
    icon: "/professional-apps/tomato-vpn.png",
    href: "https://apps.apple.com/us/app/vpn-tomatolink-fast-wifi-proxy/id6449517484",
  },
  {
    name: "Bubble VPN",
    label: "Built end-to-end",
    icon: "/professional-apps/bubble-vpn.png",
    href: "https://apps.apple.com/us/app/bubble-vpn-speed-connect-fast/id1591409499",
  },
  {
    name: "Uranus NetTest",
    label: "Built end-to-end",
    icon: "/professional-apps/uranus-nettest.png",
    href: "https://apps.apple.com/us/app/uranus-nettest-speed-test/id1585109550",
  },
  {
    name: "PunchLog",
    label: "Modernized",
    icon: "/professional-apps/punchlist.png",
  },
];

export const showcaseProjects: ShowcaseProject[] = [
  {
    slug: "33vpn",
    name: "33VPN",
    status: "UIKit architecture build",
    description: "UIKit app architecture built with MVVM and Clean Architecture.",
    category: "UIKit app architecture",
    icon: "/ui/appscreenshots/33vpn/app-icon.png",
    href: "/projects#33vpn",
    githubUrl: "https://github.com/zeeshan2k2/33VPN",
    techStack: ["Swift", "UIKit", "MVVM", "Clean Architecture", "CocoaPods"],
    preferredFrame: "phone",
    screenshots: [
      { src: "/ui/appscreenshots/33vpn/Home.png" },
      { src: "/ui/appscreenshots/33vpn/servers.png" },
      { src: "/ui/appscreenshots/33vpn/settings.png" },
      { src: "/ui/appscreenshots/33vpn/premium%201.png" },
      { src: "/ui/appscreenshots/33vpn/premium%202.png" },
      { src: "/ui/appscreenshots/33vpn/premium%203.png" },
      { src: "/ui/appscreenshots/33vpn/vpn%20protocol.png" },
      { src: "/ui/appscreenshots/33vpn/privacy%20policy.png" },
      { src: "/ui/appscreenshots/33vpn/delete%20alert.png" },
      { src: "/ui/appscreenshots/33vpn/Support.png" },
    ],
  },
  {
    slug: "weather",
    name: "Weather",
    status: "SwiftUI + widgets",
    description: "SwiftUI weather interface with forecast views, widgets, and AI summary screens.",
    category: "SwiftUI product UI",
    icon: "/ui/appscreenshots/weather/app-icon.png",
    href: "/projects#weather",
    githubUrl: "https://github.com/zeeshan2k2/Weather",
    techStack: ["Swift", "SwiftUI", "Widgets", "Forecast UI"],
    preferredFrame: "phone",
    screenshots: [
      { src: "/ui/appscreenshots/weather/weather-view.PNG" },
      { src: "/ui/appscreenshots/weather/weather-list-view.png" },
      { src: "/ui/appscreenshots/weather/day-detail-view.PNG" },
      { src: "/ui/appscreenshots/weather/ai-summary-view.PNG" },
      { src: "/ui/appscreenshots/weather/widget-medium.jpg", frame: "wide" },
      { src: "/ui/appscreenshots/weather/widget-small.jpg", frame: "square" },
    ],
  },
  {
    slug: "swift-genui",
    name: "SwiftGenUI",
    status: "AI + native UI",
    description: "Schema-driven native UI generation using local LLMs and SwiftUI.",
    category: "AI + iOS systems",
    icon: "/ui/appscreenshots/swift-genui/app-icon.png",
    href: "/projects#swift-genui",
    githubUrl: "https://github.com/zeeshan2k2/SwiftGenUI",
    techStack: ["Swift", "SwiftUI", "Local LLMs", "Schema Design"],
    preferredFrame: "phone",
    screenshots: [
      { src: "/ui/appscreenshots/swift-genui/home.png" },
      { src: "/ui/appscreenshots/swift-genui/generated%20canvas.png" },
      { src: "/ui/appscreenshots/swift-genui/schema%20inspector.png" },
      { src: "/ui/appscreenshots/swift-genui/ai%20provider.png" },
      { src: "/ui/appscreenshots/swift-genui/endpoint%20setting.png" },
      { src: "/ui/appscreenshots/swift-genui/history.png" },
    ],
  },
  {
    slug: "spatial-tutor",
    name: "Spatial Tutor",
    status: "AI + visionOS",
    description: "VisionOS AI tutor with SwiftUI, TCA, voice streaming, and session summaries.",
    category: "VisionOS product work",
    icon: "/ui/appscreenshots/spatial-tutor/app-icon.png",
    href: "/projects#spatial-tutor",
    githubUrl: "https://github.com/zeeshan2k2/Spatial-Tutor",
    techStack: ["SwiftUI", "VisionOS", "TCA", "WebSocket", "SwiftData"],
    preferredFrame: "vision",
    screenshots: [
      { src: "/ui/appscreenshots/spatial-tutor/board%20view.png" },
      { src: "/ui/appscreenshots/spatial-tutor/diargram%20board.png" },
      { src: "/ui/appscreenshots/spatial-tutor/edit profile.png" },
      { src: "/ui/appscreenshots/spatial-tutor/entry.png" },
      { src: "/ui/appscreenshots/spatial-tutor/manage.png" },
    ],
  },
];

const learningEntries: LearningProject[] = [
  {
    name: "Menu",
    category: "SwiftUI",
    description: "An iOS SwiftUI app built to explore a clean food-ordering flow with multiple screens, structured navigation, and predictable state-driven UI updates.",
    techStack: ["SwiftUI", "MVVM", "ObservableObject"],
    githubUrl: "https://github.com/zeeshan2k2/Menu",
    status: "Learning",
  },
  {
    name: "iOS Combine Examples",
    category: "Combine",
    description: "A learning-focused Swift repository exploring reactive data flow, subjects, operators, and asynchronous state handling through practical Combine examples.",
    techStack: ["Swift", "Combine", "Reactive Programming"],
    githubUrl: "https://github.com/zeeshan2k2/iOS-Combine-Examples",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Combine-GitHub-31ad7fcea3528066990eed4a6d961192",
    status: "Learning",
  },
  {
    name: "OOP in Swift",
    category: "Learning Path",
    description: "A learning-focused Swift playground repository covering core object-oriented programming concepts through focused examples and practice-driven code.",
    techStack: ["Swift", "OOP", "Playgrounds"],
    githubUrl: "https://github.com/zeeshan2k2/OOP-in-Swift/tree/main",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/OOP-in-Swift-GitHub-3cbcc0b5301948a689fadd2e02d4630c?source=copy_link",
    status: "Learning Path",
  },
  {
    name: "Widget Kit",
    category: "WidgetKit",
    description: "A simple SwiftUI learning project built to understand widget families, timeline-based updates, and the core WidgetKit flow in iOS.",
    techStack: ["Swift", "SwiftUI", "WidgetKit"],
    githubUrl: "https://github.com/zeeshan2k2/Widget-Kit",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/WidgetKit-284d7fcea352803eb73bef1b9c60dace?source=copy_link",
    status: "Learning",
  },
  {
    name: "LazyLab",
    category: "SwiftUI Internals",
    description: "A SwiftUI experimentation project built to study lazy containers, rendering behavior, diffing, identity, and state-driven updates under the hood.",
    techStack: ["SwiftUI", "LazyVStack", "LazyVGrid"],
    githubUrl: "https://github.com/zeeshan2k2/LazyLab",
    notionUrl:
      "https://secretive-fascinator-c6c.notion.site/8-Lazy-Containers-LazyVStack-LazyHStack-LazyVGrid-LazyHGrid-330d7fcea352802987e5fbd47c5cf061?source=copy_link",
    status: "Learning",
  },
  {
    name: "iOS Notifications Examples",
    category: "UserNotifications",
    description: "A learning-focused Swift repository exploring notification permissions, local notifications, scheduling, actions, and notification handling through practical examples.",
    techStack: ["Swift", "UIKit", "UserNotifications"],
    githubUrl: "https://github.com/zeeshan2k2/iOS-Notifications-Examples",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Notifications-31ad7fcea352807e95cddd437ab61ace?source=copy_link",
    status: "Learning",
  },
  {
    name: "Go-Swift Integration",
    category: "Interop",
    description: "A macOS integration project showing how to statically link Go code into a Swift app using cgo, a generated C header, and a bridging header workflow.",
    techStack: ["Go", "Swift", "cgo"],
    githubUrl: "https://github.com/zeeshan2k2/GoWrapperMacApp",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/GO-Wrapper-in-Swift-126d7fcea35280e3aa7eff0076d13135?pvs=4",
    status: "Learning",
  },
  {
    name: "Infinite Image Feed",
    category: "Feed UI",
    description: "A Swift project exploring infinite scrolling, paginated image loading, asynchronous updates, and reusable feed patterns for large content lists.",
    techStack: ["Swift", "MVVM", "URLSession"],
    githubUrl: "https://github.com/zeeshan2k2/Infinite-Image-Feed",
    status: "Learning",
  },
  {
    name: "Passkey",
    category: "Authentication",
    description: "Implementation notes covering Passkey registration and authentication on iOS, from Authentication Services and WebAuthn theory to backend validation and real-device setup details.",
    techStack: ["Passkeys", "AuthenticationServices", "WebAuthn"],
    notionUrl: "https://app.notion.com/p/Passkey-2bfd7fcea35280e598f7cf55e5b6e885?source=copy_link",
    status: "Research",
  },
  {
    name: "NavKit",
    category: "Navigation",
    description: "A Swift learning project focused on navigation patterns, screen flow, and state-driven movement across app views.",
    techStack: ["Swift", "SwiftUI", "NavigationStack"],
    githubUrl: "https://github.com/zeeshan2k2/NavKit",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/9-Navigation-334d7fcea3528088af74d8d578a112bd",
    status: "Learning",
  },
  {
    name: "iOS Networking Examples",
    category: "Networking",
    description: "A learning-focused Swift repository exploring API communication, request handling, decoding, validation, and asynchronous networking patterns in iOS apps.",
    techStack: ["Swift", "URLSession", "Codable"],
    githubUrl: "https://github.com/zeeshan2k2/iOS-Networking-Examples",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Networking-327d7fcea35280a9b432d591343ac155?source=copy_link",
    status: "Learning",
  },
  {
    name: "Call Kit",
    category: "CallKit",
    description: "A learning-focused Swift repository exploring native iOS calling flows, CallKit configuration, call lifecycle handling, and VoIP-style system integrations.",
    techStack: ["Swift", "CallKit", "AVFoundation"],
    githubUrl: "https://github.com/zeeshan2k2/Call-Kit",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/CallKit-5-hours-321d7fcea352806f8d0fd155f2fc8aa2?source=copy_link",
    status: "Learning",
  },
  {
    name: "ByteForge",
    category: "Compression Research",
    description: "An experimental C++ project exploring whether quantized `.gguf` model files contain enough byte-level structure for meaningful lossless compression through custom binary formats and validation-heavy research.",
    techStack: ["C++", "GGUF", "Binary Formats"],
    githubUrl: "https://github.com/zeeshan2k2/ByteForge",
    notionUrl:
      "https://secretive-fascinator-c6c.notion.site/Project-Name-ByteForge-In-progress-GitHub-357d7fcea352808ea5aed6d20c8e21be?source=copy_link",
    status: "Research",
  },
  {
    name: "Sean Allen UIKit Notes",
    category: "Learning Path",
    description: "Personal notes from Sean Allen's UIKit course, covering practical iOS foundations like layout, lifecycle, view controllers, debugging habits, and UIKit workflow details.",
    techStack: ["UIKit", "Auto Layout", "View Controllers"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Swift-UIKit-Sean-Allen-Swift-Course-4ee780fb53504aa1b64ca1a35c073c0b?source=copy_link",
    status: "Learning Path",
  },
  {
    name: "100 Days of Swift",
    category: "Learning Path",
    description: "Structured Swift foundation notes based on Paul Hudson's 100 Days of Swift, covering language basics, control flow, functions, closures, structs, classes, protocols, optionals, and early projects.",
    techStack: ["Swift", "Foundations", "Practice"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/100-days-of-Swift-Paul-Hudson-course-5cf9bd49c6f34a80a475b7eba7a5c8e3?source=copy_link",
    status: "Learning Path",
  },
  {
    name: "SwiftUI Learning Path",
    category: "Learning Path",
    description: "Self-driven SwiftUI notes and experiments focused on layout, rendering behavior, navigation, component patterns, and building a stronger mental model of declarative UI.",
    techStack: ["SwiftUI", "Navigation", "Layout"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/SwiftUI-321d7fcea35280689abec1623ccdc45f?source=copy_link",
    status: "Learning Path",
  },
  {
    name: "GraphQL Lab",
    category: "GraphQL",
    description: "A learning-focused Swift repository exploring GraphQL queries, mutations, schema-driven APIs, and strongly typed data fetching in iOS applications.",
    techStack: ["Swift", "GraphQL", "Codable"],
    githubUrl: "https://github.com/zeeshan2k2/GraphQL-Lab",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/GraphQL-321d7fcea35280ad9f30fe95eb40bbd1?source=copy_link",
    status: "Learning",
  },
  {
    name: "Swift Data Flow",
    category: "UIKit Patterns",
    description: "A learning-focused Swift repository exploring forward and backward data passing between view controllers using property assignment, callbacks, and delegate-based communication.",
    techStack: ["Swift", "UIKit", "Delegates"],
    githubUrl: "https://github.com/zeeshan2k2/Swift-Data-Flow",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Data-Passing-in-Swift-UIKit-GitHub-2f1d7fcea35280e5a7a3c993ca07328d",
    status: "Learning",
  },
  {
    name: "Core Data Demo",
    category: "Persistence",
    description: "A learning-focused Swift repository exploring local persistence with Core Data, including CRUD operations, fetch requests, predicates, and the Core Data stack.",
    techStack: ["Swift", "Core Data", "UIKit"],
    githubUrl: "https://github.com/zeeshan2k2/CoreData-demo",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Core-Data-GitHub-311d7fcea352807bb8fae0c027694ad4?source=copy_link",
    status: "Learning",
  },
  {
    name: "Checklists",
    category: "UIKit App",
    description: "An iOS checklist app for creating, editing, and organizing lists and sub-lists, with reminders, date editing, and notification support.",
    techStack: ["Swift", "UIKit", "MVC"],
    githubUrl: "https://github.com/zeeshan2k2/Checklists",
    status: "Learning",
  },
  {
    name: "SnapCast",
    category: "Computer Vision",
    description: "A prototype for gesture-based screenshot sharing between Macs over a local network using computer vision, UDP discovery, and peer-to-peer file transfer.",
    techStack: ["Python", "OpenCV", "MediaPipe"],
    githubUrl: "https://github.com/zeeshan2k2/SnapCast",
    status: "Prototype",
  },
  {
    name: "Money Tracker",
    category: "SwiftData",
    description: "A Swift-based money tracking project exploring SwiftData persistence patterns for managing, storing, and organizing personal finance records.",
    techStack: ["Swift", "SwiftUI", "SwiftData"],
    githubUrl: "https://github.com/zeeshan2k2/Money-Tracker/tree/swift-data",
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Swift-Data-2fbd7fcea352809d89fcf3aef8f72f18?source=copy_link",
    status: "Learning",
  },
  {
    name: "UIViewController Life Cycle",
    category: "UIKit Internals",
    description: "A notes-first deep dive into the UIViewController lifecycle, covering method order, setup responsibilities, observer timing, cleanup patterns, layout method boundaries, and deallocation behavior.",
    techStack: ["UIKit", "View Controllers", "Lifecycle"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/UIViewController-Life-Cycle-2f0d7fcea352801fa461c0b06cd9af65?source=copy_link",
    status: "Learning",
  },
  {
    name: "Auto Layout (UIKit)",
    category: "UIKit Internals",
    description: "A notes-first deep dive into Auto Layout, covering constraints, intrinsic content size, hugging and compression priorities, ambiguous layouts, conflict resolution, and debugging layout failures.",
    techStack: ["UIKit", "Auto Layout", "Debugging"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Auto-Layout-UIKit-2f0d7fcea35280aaa4e6cfa3e7c91078?source=copy_link",
    status: "Learning",
  },
  {
    name: "iOS App Lifecycle",
    category: "App Lifecycle",
    description: "A notes-first deep dive into iOS app lifecycle behavior, covering app states, AppDelegate and SceneDelegate responsibilities, pause and resume timing, memory behavior, and real-world lifecycle handling.",
    techStack: ["iOS", "AppDelegate", "SceneDelegate"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/iOS-App-Lifecycle-2f0d7fcea352801c8b39df3fb342cc05?source=copy_link",
    status: "Learning",
  },
  {
    name: "Stack vs Heap",
    category: "Memory",
    description: "A notes-first deep dive into stack and heap memory in Swift and iOS, covering value vs reference semantics, copy-on-write, ARC boundaries, and the practical performance implications for app code.",
    techStack: ["Swift", "Memory", "ARC"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Stack-vs-Heap-Swift-iOS-2f0d7fcea3528088b190dc3778d0c638?source=copy_link",
    status: "Learning",
  },
  {
    name: "SOLID Principles",
    category: "Architecture",
    description: "A notes-first learning card covering the SOLID principles and how they shape maintainable Swift code, better abstractions, and cleaner module boundaries.",
    techStack: ["Architecture", "Abstractions", "Maintainability"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Solid-Principles-cb92c98ff83945b99231245197e24500?source=copy_link",
    status: "Learning",
  },
  {
    name: "Dependency Injection",
    category: "Architecture",
    description: "A notes-first learning card covering dependency injection in Swift, including constructor, property, and method injection, with a focus on decoupling and testability.",
    techStack: ["Dependency Injection", "Protocols", "Testability"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Dependency-Injection-0b4a3070427443ebbc5f77f0eba03fc4?source=copy_link",
    status: "Learning",
  },
  {
    name: "Generics",
    category: "Swift Fundamentals",
    description: "A notes-first learning card covering generics in Swift, with a focus on reusable functions, generic types, constraints, and type-safe abstractions.",
    techStack: ["Swift", "Generics", "Type Safety"],
    notionUrl: "https://secretive-fascinator-c6c.notion.site/Generics-e1bb7f4f1a804c4e8847a0e3261e91a5?source=copy_link",
    status: "Learning",
  },
];

export const learningPaths = learningEntries.filter((entry) => entry.status === "Learning Path");
export const orderedLearningPaths = [
  "Sean Allen UIKit Notes",
  "100 Days of Swift",
  "SwiftUI Learning Path",
  "OOP in Swift",
].flatMap((name) => learningPaths.filter((entry) => entry.name === name));

export const technicalNotes = learningEntries.filter(
  (entry) => !entry.githubUrl && entry.status !== "Learning Path",
);

export const learningProjects = learningEntries.filter(
  (entry) => Boolean(entry.githubUrl) && entry.status !== "Learning Path",
);
